### ISSUE TITLE
Compiling Shell Elastic FEM plugin on Windows 11 system

### ISSUE THREAD

**Issue by julien-siguenza** [SofaDefrost/Shell#2]
Hi there!

I am currently facing some issues to compile the Shell Elastic FEM plugin on my Windows 11 system, considering the [out-of-tree build](https://www.sofa-framework.org/community/doc/plugins/build-a-plugin-from-sources/) methodology:

1. I first download SOFA Framework (version 24.06.00) [from binaries](https://www.sofa-framework.org/community/doc/getting-started/binaries/binaries-instructions/).
2. Then, I clone the git repository of the plugin in a separated folder. It seems that there is only one branch for this plugin (the main branch), so I hope it is compatible with the downloaded version of SOFA.
3. I create a `build` folder within the cloned folder.
4. I download [CMake (cmake-gui)](https://cmake.org/download/) (version 3.22.1) from binaries, as well as Visual Studio 2022.
5. I launch cmake-gui, define the cloned folder as source code and the created `build` folder as the location to build binaries.
6. I add an entry to define the `CMAKE_PREFIX_PATH`, which points to the `lib/cmake` folder of the SOFA installation (note that the `SOFA_ROOT` environment variable has also been set previously). 
7. When I press the _Configure_ button, CMake is asking me to specify the generator. I let the default generator, in my case Visual Studio 17 2022. I keep the pre-defined option "Use default native compilers" and press _Finish_.

I finally end up with the following error messages:

![image](https://github.com/user-attachments/assets/c18473e5-dd15-48ca-bc4f-f47a5ed495e5)

I also attach here the [CMakeOutput.log](https://github.com/user-attachments/files/16500473/CMakeOutput.log) file.

Could you please help me solve this issue?

Many thanks!

FYI: @hugtalbot @bakpaul @consortium-staff

**Comment by alxbilger** [comment]
Hi,

> It seems that there is only one branch for this plugin (the main branch), so I hope it is compatible with the downloaded version of SOFA.

Well, it's not... Thanks for reporting the problem.

I'll let you know when it's fixed.

**Comment by alxbilger** [comment]
It should be fixed now. Let us know if it works for you

**Comment by julien-siguenza** [comment]
Thanks for fixing the bug @alxbilger!
I can now properly compile the plugin.

But I still have some misunderstandings about the way to use the plugin.

The [SOFA documentation](https://www.sofa-framework.org/community/doc/plugins/build-a-plugin-from-sources/) explains that the `CMAKE_INSTALL_PREFIX` variable should be defined when configuring the compilation, so that the plugin can be installed directly into the SOFA installation.

So I define this variable to points towards the `plugins/Shell` folder of my SOFA installation (I created the `Shell` folder manually in there, just in case) but it looks like nothing appears after compiling the plugin.

Can you please enlighten me on this?

Many thanks!

**Comment by julien-siguenza** [comment]
Well, so what's the purpose of the `CMAKE_INSTALL_PREFIX` varibale during the CMake configuration?

**Comment by alxbilger** [comment]
It tells the solution where to install when you run the install target. I rephrase: if you don't run the install target I mentioned, you will only compile, not install.

**Comment by julien-siguenza** [comment]
Sorry @alxbilger it seems that I am reaching my limits of understanding in terms of IT haha!

I did not compile that much of projects in the past.
But when I compile a project, I usually generate only the `ALL_BUILD.vcxproj` with Visual Studio, and it is then building everything in the `build` folder defined in CMake.

So I now also generated the `INSTALL.vcxproj` and it seems that everything is installed properly within the `plugins/Shell` folder.

I still have a last question to address with you.
I now try to run SOFA and load the test scene `ShellTest.scn`, but I end up with the following error message:

![image](https://github.com/user-attachments/assets/d293a513-ce94-406a-9f34-a579de5c3f4b)

Just to see, I tried to delete the line 5 that seems to be problematic.
The scene is then loaded properly, but nothing is happening when I animate the scene.

**Comment by julien-siguenza** [comment]
All good!

Everything is working properly now:

![image](https://github.com/user-attachments/assets/1b7a0eb4-2b6f-42de-9903-fe4036660898)

Thanks for your help @alxbilger :pray:

**Comment by julien-siguenza** [comment]
Sorry for bothering you again @alxbilger but it seems I experience something very weird when I try to launch the scene using the python API.

I tried to replicate the xml scene within a .py file, with the following code:

```
import Sofa
import Sofa.Gui

def main():

    root = Sofa.Core.Node("root")

    createScene(root)

    Sofa.Simulation.init(root)

    Sofa.Gui.GUIManager.Init('myscene', 'qglviewer')
    Sofa.Gui.GUIManager.createGUI(root, __file__)
    Sofa.Gui.GUIManager.SetDimension(1080, 1080)
    Sofa.Gui.GUIManager.MainLoop(root)
    Sofa.Gui.GUIManager.closeGUI()

def createScene(rootNode):

    rootNode.addObject('RequiredPlugin', name="Shell")
    rootNode.addObject('RequiredPlugin', name="Sofa.Component.Constraint.Projective")
    rootNode.addObject('RequiredPlugin', name="Sofa.Component.Engine.Select")
    rootNode.addObject('RequiredPlugin', name="Sofa.Component.IO.Mesh")
    rootNode.addObject('RequiredPlugin', name="Sofa.Component.LinearSolver.Direct")
    rootNode.addObject('RequiredPlugin', name="Sofa.Component.Mapping.Linear")
    rootNode.addObject('RequiredPlugin', name="Sofa.Component.Mass")
    rootNode.addObject('RequiredPlugin', name="Sofa.Component.ODESolver.Backward")
    rootNode.addObject('RequiredPlugin', name="Sofa.Component.StateContainer")
    rootNode.addObject('RequiredPlugin', name="Sofa.Component.Topology.Container.Constant")
    rootNode.addObject('RequiredPlugin', name="Sofa.Component.Visual")
    rootNode.addObject('RequiredPlugin', name="Sofa.GL.Component.Rendering3D")
    rootNode.addObject('RequiredPlugin', name="Sofa.GUI.Component")

    rootNode.gravity = [0, -98.1, 0]
    rootNode.time = 0
    rootNode.animate = 0
    rootNode.addObject('AttachBodyButtonSetting', stiffness=0.1)
    rootNode.addObject('DefaultAnimationLoop')

    rootNode.addObject('VisualStyle',
        displayFlags=[
            "hideVisualModels",
            "hideBehaviorModels",
            "showMappings",
            "showForceFields"
        ]
    )

    square = rootNode.addChild('Square')
    square.addObject('EulerImplicitSolver')
    square.addObject('SparseLDLSolver',
        template="CompressedRowSparseMatrixMat3x3d",
    )
    square.addObject('MeshOBJLoader', name="loader", filename='mesh/square1.obj')
    square.addObject('MeshTopology', name="topology", src="@loader")
    square.addObject('MechanicalObject', template='Rigid3')
    square.addObject('UniformMass', totalMass=0.005)
    square.addObject('BoxROI', name="box", box=[0, 0.9, -0.1, 1, 1, 0.1], drawBoxes=True)
    square.addObject('FixedConstraint', indices="@box.indices")
    square.addObject('TriangularBendingFEMForceField', youngModulus=1.7e3,
                     poissonRatio=0.3, thickness=0.01)

    visu = square.addChild('Visu')
    visu.addObject('OglModel', src="@../topology")
    visu.addObject('IdentityMapping')

if __name__ == '__main__':
    
    main()
```

When I then run the python script, the scene is launched correctly, but I then animate it and try to sollicitate the plate using the SHIFT+click interaction, and the deformation of the plate is completely crashing.

Can you please try to run my python script from your side and tell me what's happening?

Maybe I am missing something obvious there :persevere:
